name: Build, Scan, and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: akira-erp-repo
  IMAGE_TAG: latest

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Configure AWS credentials from GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.FIRST_SECRET }}
        aws-secret-access-key: ${{ secrets.SECOND_SECRET }}
        aws-region: ${{ env.AWS_REGION }}

    # 3️⃣ Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

    # 5️⃣ Scan Docker image using Trivy (open-source scanner)
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        format: 'table'
        exit-code: '0'

    # 6️⃣ Push image to ECR
    - name: Push image to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI
        docker push $IMAGE_URI

